global:
  resolve_timeout: 15m
receivers:
- name: devnull
- name: prometheus-msteams-warning
  webhook_config:
  - url: "http://prometheus-msteams:2000/alertmanager-warning"
    send_resolved: true
- name: prometheus-msteams-critical
  webhook_config:
  - url: "http://prometheus-msteams:2000/alertmanager-critical"
route:
  group_by: ['...']
  group_interval: 1m
  group_wait: 1m
  receiver: devnull
  repeat_interval: 5m
  routes:
  - receiver: prometheus-msteams-warning
    match:
      severity: warning
    continue: true
  - receiver: prometheus-msteams-critical
    match:
      severity: critical
